### ISSUE TITLE
nopssdk?

### ISSUE THREAD

**Issue by ClaudeLib** [iArtorias/iArtorias#1]
<details> 
<summary>Terribly sorry for creating an issue like that, but I'm curious why that repo disappeared without a trace, along with the NexusMods page. Did Sony take it down?</summary>
Thankfully I managed to grab v1.0.3, which does indeed work on Linux, thanks a ton!
</details>

**Comment by iArtorias** [comment]
Nothing much to say, both IGN and NexusMods just made the post.
